apiVersion: v1
kind: Secret
metadata:
  name: erlang-cookie
  namespace: test-rabbitmq
  annotations:
    kubernetes.io/service-account.name: "rabbitmq"
# type: kubernetes.io/service-account-token
data:
  # You can include additional key value pairs as you do with Opaque Secrets
  cookie: cmFiYml0TXFFcmxhbmdDb29raWUxMjM=

---

apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-admin
  namespace: test-rabbitmq
  annotations:
    kubernetes.io/service-account.name: "rabbitmq"
# type: kubernetes.io/service-account-token
data:
  # You can include additional key value pairs as you do with Opaque Secrets
  user: YWRtaW5pc3RyYXRvcg==
  pass: ZzNOM3JBdEVELVBhNTk4OHcwcmQ=